## 2. Linear regression on house dataset

Use this dataset on house price prediction in kaggle, perform EDA on it and then predict the house prices using linear regression. You can drop the categorical features and the date columns. Then try ElasticNetCV and RidgeCV on the same dataset. Record the scores in a dataframe with the columns mae, mse, rmse so you can compare the models.

In [11]:
import pandas as pd

df = pd.read_csv("../data/house_price_data.csv")
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [12]:
df.shape

(4600, 18)

In [13]:
df.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [14]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

## Ta bort kategoriska värden (icke numeriska)

In [15]:
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [19]:
df = df.drop(["date", "street", "city", "statezip", "country"], axis="columns")
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0     0          3        1340              0      1955          2005  
1     4          5        3370            280      1921             0  
2     0          4        1930              0      1966             0  
3     0          4        1000           1000      1963             0  
4     0          4        1140            800      1976          1992

## Olika sätt att göra regression
- LinearRegression	Ingen	Vanlig OLS, kan överanpassa om många features
- RidgeCV	L2	Stramar åt koefficienterna, minskar överanpassning
- ElasticNetCV	L1 + L2	Både sparsity och stabilitet, bra om många features

In [20]:
df.shape
print(f"Antal rader = {df.shape[0]}")
print(f"Antal features = {df.shape[1] - 1}")
print(f"Label/target = price")

Antal rader = 4600
Antal features = 12
Label/target = mpg


## Dela upp X och y, X blir feature, y blir label

In [21]:
X, y = df.drop("price", axis="columns"), df["price"]
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0       3.0       1.50         1340      7912     1.5           0     0   
1       5.0       2.50         3650      9050     2.0           0     4   
2       3.0       2.00         1930     11947     1.0           0     0   
3       3.0       2.25         2000      8030     1.0           0     0   
4       4.0       2.50         1940     10500     1.0           0     0   

   condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0          3        1340              0      1955          2005  
1          5        3370            280      1921             0  
2          4        1930              0      1966             0  
3          4        1000           1000      1963             0  
4          4        1140            800      1976          1992

In [22]:
y.head()

0     313000.0
1    2384000.0
2     342000.0
3     420000.0
4     550000.0
Name: price, dtype: float64

In [23]:
from sklearn.model_selection import train_test_split
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.

    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        com

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [25]:
print(f"{X_train.shape = }")
print(f"{y_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (3082, 12)
y_train.shape = (3082,)
X_test.shape = (1518, 12)
y_test.shape = (1518,)


In [26]:
X_train.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
4351       2.0       1.00          780     16344     1.0           0     0   
3560       3.0       1.00          910      8789     1.0           0     0   
2589       4.0       2.50         1740      7500     1.0           0     0   
3062       3.0       2.75         1100       750     2.0           0     0   
4434       4.0       2.75         2320      4344     2.0           0     0   

      condition  sqft_above  sqft_basement  yr_built  yr_renovated  
4351          1         780              0      1942             0  
3560          3         910              0      1966          1963  
2589          4        1220            520      1976          1992  
3062          3         780            320      2008             0  
4434          3        2320              0      2012          1912

In [27]:
y_train.head()

4351      7800.000000
3560    221000.000000
2589    518000.000000
3062    286000.000000
4434    484991.666667
Name: price, dtype: float64

## SCALE

In [28]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler

MinMaxScaler()

In [29]:
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min() = }")
print(f"{scaled_X_train.max() = }")

scaled_X_train.min() = np.float64(0.0)
scaled_X_train.max() = np.float64(1.0)


In [30]:
print(f"{scaled_X_test.min() = }")
print(f"{scaled_X_test.max() = }")

scaled_X_test.min() = np.float64(-6.148033467658553e-05)
scaled_X_test.max() = np.float64(1.3619441571871767)


In [31]:
scaled_X_train.shape

(3082, 12)

In [32]:
scaled_X_train[:5]

array([[2.22222222e-01, 1.48148148e-01, 4.23991727e-02, 1.45689763e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.35947712e-02, 0.00000000e+00, 3.68421053e-01, 0.00000000e+00],
       [3.33333333e-01, 1.48148148e-01, 5.58428128e-02, 7.53134100e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        7.05882353e-02, 0.00000000e+00, 5.78947368e-01, 9.74677259e-01],
       [4.44444444e-01, 3.70370370e-01, 1.41675284e-01, 6.33061143e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.50000000e-01,
        1.11111111e-01, 1.07883817e-01, 6.66666667e-01, 9.89076465e-01],
       [3.33333333e-01, 4.07407407e-01, 7.54912099e-02, 4.28499302e-05,
        4.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        5.35947712e-02, 6.63900415e-02, 9.47368421e-01, 0.00000000e+00],
       [4.44444444e-01, 4.07407407e-01, 2.01654602e-01, 3.39073361e-03,
        4.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00

In [33]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model

LinearRegression()

In [34]:
model.fit(scaled_X_train, y_train)
print(f"Parameters or weights: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Parameters or weights: [-632961.81002926  183976.01614267 1331571.73914542 -530140.69848596
  177191.62069176  399702.99214839  168311.44859383  121549.92982669
 1215092.06710175  742913.77680659 -296813.44004883   11894.27813395]
Intercept: 265073.54098144686


## Prediction

In [35]:
X_test.iloc[0]

bedrooms            3.0
bathrooms           2.5
sqft_living      1460.0
sqft_lot         1613.0
floors              2.0
waterfront          0.0
view                0.0
condition           3.0
sqft_above       1180.0
sqft_basement     280.0
yr_built         2007.0
yr_renovated        0.0
Name: 3683, dtype: float64

In [36]:
sample_features = scaled_X_test[0].reshape(1, -1)
sample_features

array([[3.33333333e-01, 3.70370370e-01, 1.12719752e-01, 8.46751882e-04,
        4.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        1.05882353e-01, 5.80912863e-02, 9.38596491e-01, 0.00000000e+00]])

In [37]:
model.predict(sample_features)

array([296748.2583545])

In [38]:
y_test.iloc[0]

np.float64(544000.0)

## Prediction on everything

In [39]:
y_pred = model.predict(scaled_X_test)
y_pred[:5]

array([ 296748.2583545 ,  318512.5986427 , 1067958.25109663,
        551073.20614371,  371726.21302356])

In [40]:
y_test.iloc[:5]

3683     544000.0
4411          0.0
2584    1712500.0
69       365000.0
1844     275000.0
Name: price, dtype: float64

## EVALUATE

In [41]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"{mae = }")
print(f"{mse = }")
print(f"{rmse = }")

mae = 191902.15686061102
mse = 621380924636.5221
rmse = np.float64(788277.1876925795)


## Använd RidgeCV


In [47]:
from sklearn.linear_model import RidgeCV

def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    
    return {"mae": mae, "mse": mse, "rmse": rmse}


## RidgeCV

In [43]:
ridge = RidgeCV(alphas=[0.1, 1.0, 10.0])  # lista med olika alpha-värden som RidgeCV testar
ridge_results = evaluate_model(ridge, X_train, X_test, y_train, y_test)
print("RidgeCV:", ridge_results)

RidgeCV: {'mae': 192135.77771693264, 'mse': 621284694126.8799, 'rmse': np.float64(788216.1468321236)}


## Spara resultat visa dem

## Terminology	Meaning
- supervised learning	- maskinen lär från data där både features och labels är kända
- machine learning    - Ai där datorer lär sig mönster i data utan att programmeras för varje enskild uppgift 	 
- data science	    - Analysera data, få insikter och kunskap, statistik osv
- data engineering	- Hanterar datan, strukturerar och gör den användbar
- algorithm	        - Ett antal steg eller regler för att utföra en uppgift
- regression	        - förutspå ett kontinuerligt värde
- classification	    - gruppera, kategorisera
- qualitative data	- beskriver kvaliteer/egenskaper
- quantitative data	- beskriver numeriska värden, typ huspris, lön, ålder osv
- independent variable- features, t.ex. område, antal rum osv
- dependent variable	- label/target, t.ex. pris
- label	            - det vi vill predicta
- feature	            - det som påverkar prediktionen
- model	            - en matematiskt represenatation som lär sig mönster från data föra tt göra rpediktioner
- training	        - låt modellen träna på en viss del av data för att hitta mönster, innan själva testet på okänd data
- evaluation	        - utvärdera resultatet, t.ex. MAE,MSE,RMSE
- prediction	        - förutsägelse på nya eller okända data