## 2. Linear regression on house dataset

Use this dataset on house price prediction in kaggle, perform EDA on it and then predict the house prices using linear regression. You can drop the categorical features and the date columns. Then try ElasticNetCV and RidgeCV on the same dataset. Record the scores in a dataframe with the columns mae, mse, rmse so you can compare the models.

In [69]:
import pandas as pd

df = pd.read_csv("../data/house_price_data.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA


In [70]:
df = df.query("price > 0")

In [71]:
df.shape

(4551, 18)

In [72]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.551000e+03,4551.000000,4551.000000,4551.000000,4.551000e+03,4551.000000,4551.000000,4551.000000,4551.000000,4551.000000,4551.000000,4551.000000,4551.000000
mean,5.579059e+05,3.394639,2.155021,2132.372226,1.483528e+04,1.512195,0.006592,0.234674,3.449352,1822.221710,310.150516,1970.795649,808.564052
std,5.639299e+05,0.904595,0.776351,955.949708,3.596408e+04,0.538531,0.080932,0.765373,0.675160,854.452888,461.987629,29.760073,979.421487
min,7.800000e+03,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.262643e+05,3.000000,1.750000,1460.000000,5.000000e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.650000e+05,3.000000,2.250000,1970.000000,7.680000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.575000e+05,4.000000,2.500000,2610.000000,1.097800e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,600.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000


In [73]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

## Ta bort kategoriska värden (icke numeriska)

In [74]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA


In [75]:
df = df.drop(["date", "street", "city", "statezip", "country"], axis="columns")
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992


## Olika sätt att göra regression
- LinearRegression	Ingen	Vanlig OLS, kan överanpassa om många features
- RidgeCV	L2	Stramar åt koefficienterna, minskar överanpassning
- ElasticNetCV	L1 + L2	Både sparsity och stabilitet, bra om många features

In [76]:
df.shape
print(f"Antal rader = {df.shape[0]}")
print(f"Antal features = {df.shape[1] - 1}")
print(f"Label/target = price")

Antal rader = 4551
Antal features = 12
Label/target = price


## Dela upp X och y, X blir feature, y blir label

In [77]:
X, y = df.drop("price", axis="columns"), df["price"]
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992


In [78]:
y.head()

0     313000.0
1    2384000.0
2     342000.0
3     420000.0
4     550000.0
Name: price, dtype: float64

In [79]:
from sklearn.model_selection import train_test_split
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.

    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        com

In [80]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [81]:
print(f"{X_train.shape = }")
print(f"{y_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (3049, 12)
y_train.shape = (3049,)
X_test.shape = (1502, 12)
y_test.shape = (1502,)


In [82]:
X_train.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
1298,2.0,2.50,750,1430,2.0,0,0,3,750,0,2006,0
3663,4.0,3.00,2440,9664,2.0,0,0,3,1890,550,1981,2013
898,3.0,2.25,2030,7350,1.0,0,0,4,1190,840,1977,0
4085,4.0,1.75,2100,11942,1.0,0,0,3,1030,1070,1964,2000
4176,3.0,1.50,1460,9908,1.0,0,0,3,1460,0,1952,2008


In [83]:
y_train.head()

1298    375000.0
3663    480000.0
898     588000.0
4085    368000.0
4176    310000.0
Name: price, dtype: float64

## SCALE

In [84]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler

,feature_range,"(0, ...)"
,copy,True
,clip,False


In [85]:
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min() = }")
print(f"{scaled_X_train.max() = }")

scaled_X_train.min() = np.float64(0.0)
scaled_X_train.max() = np.float64(1.0)


In [86]:
print(f"{scaled_X_test.min() = }")
print(f"{scaled_X_test.max() = }")

scaled_X_test.min() = np.float64(-0.0013698630136986314)
scaled_X_test.max() = np.float64(1.8901960784313725)


In [87]:
scaled_X_train.shape

(3049, 12)

In [88]:
scaled_X_train[:5]

array([[2.22222222e-01, 3.84615385e-01, 3.83022774e-02, 6.76283681e-04,
        4.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        5.06849315e-02, 0.00000000e+00, 9.29824561e-01, 0.00000000e+00],
       [4.44444444e-01, 4.61538462e-01, 2.13250518e-01, 8.34642119e-03,
        4.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        2.06849315e-01, 2.15686275e-01, 7.10526316e-01, 9.99503476e-01],
       [3.33333333e-01, 3.46153846e-01, 1.70807453e-01, 6.19088340e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.50000000e-01,
        1.10958904e-01, 3.29411765e-01, 6.75438596e-01, 0.00000000e+00],
       [4.44444444e-01, 2.69230769e-01, 1.78053830e-01, 1.04684243e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        8.90410959e-02, 4.19607843e-01, 5.61403509e-01, 9.93048659e-01],
       [3.33333333e-01, 2.30769231e-01, 1.11801242e-01, 8.57371213e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.00

In [89]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [90]:
model.fit(scaled_X_train, y_train)
print(f"Parameters or weights: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Parameters or weights: [-586157.04720056  473521.94584601 1050222.0884748  -831382.29796539
   46112.63890542  498031.53052365  212437.73468095  185013.32744354
 1284052.4597757   302573.49737409 -268682.56139825   14302.07150357]
Intercept: 179993.30113394832


## Prediction

In [91]:
X_test.iloc[0]

bedrooms              4.0
bathrooms             4.5
sqft_living        5420.0
sqft_lot         101930.0
floors                1.0
waterfront            0.0
view                  0.0
condition             3.0
sqft_above         3890.0
sqft_basement      1530.0
yr_built           2001.0
yr_renovated          0.0
Name: 471, dtype: float64

In [92]:
sample_features = scaled_X_test[0].reshape(1, -1)
sample_features

array([[0.44444444, 0.69230769, 0.52173913, 0.09429407, 0.        ,
        0.        , 0.        , 0.5       , 0.48082192, 0.6       ,
        0.88596491, 0.        ]])

In [93]:
model.predict(sample_features)

array([1370257.4919046])

In [94]:
y_test.iloc[0]

np.float64(1225000.0)

## Prediction on everything

In [95]:
y_pred = model.predict(scaled_X_test)
y_pred[:5]

array([1370257.4919046 ,  608251.99107973,  657977.77818934,
        279447.06287658,  522732.44380393])

In [96]:
y_test.iloc[:5]

471     1225000.0
2518     496752.0
23       612500.0
3922     265000.0
135      615000.0
Name: price, dtype: float64

## EVALUATE

In [97]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"{mae = }")
print(f"{mse = }")
print(f"{rmse = }")

mae = 158370.37304234502
mse = 53255714398.187004
rmse = np.float64(230771.99656411304)


## Använd RidgeCV


In [98]:
from sklearn.linear_model import RidgeCV

def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    
    return {"mae": mae, "mse": mse, "rmse": rmse}


## RidgeCV

In [99]:
ridge = RidgeCV(alphas=[0.1, 1.0, 10.0])  # lista med olika alpha-värden som RidgeCV testar
ridge_results = evaluate_model(ridge, X_train, X_test, y_train, y_test)
print("RidgeCV:", ridge_results)

RidgeCV: {'mae': 158590.13972095627, 'mse': 53385167885.37591, 'rmse': np.float64(231052.305518417)}


## Spara resultat visa dem

## Terminology	Meaning
- supervised learning	- maskinen lär från data där både features och labels är kända
- machine learning    - Ai där datorer lär sig mönster i data utan att programmeras för varje enskild uppgift 	 
- data science	    - Analysera data, få insikter och kunskap, statistik osv
- data engineering	- Hanterar datan, strukturerar och gör den användbar
- algorithm	        - Ett antal steg eller regler för att utföra en uppgift
- regression	        - förutspå ett kontinuerligt värde
- classification	    - gruppera, kategorisera
- qualitative data	- beskriver kvaliteer/egenskaper
- quantitative data	- beskriver numeriska värden, typ huspris, lön, ålder osv
- independent variable- features, t.ex. område, antal rum osv
- dependent variable	- label/target, t.ex. pris
- label	            - det vi vill predicta
- feature	            - det som påverkar prediktionen
- model	            - en matematiskt represenatation som lär sig mönster från data föra tt göra rpediktioner
- training	        - låt modellen träna på en viss del av data för att hitta mönster, innan själva testet på okänd data
- evaluation	        - utvärdera resultatet, t.ex. MAE,MSE,RMSE
- prediction	        - förutsägelse på nya eller okända data

Skulle kunna ta bort sqft_above och sqft_basement då de beskriver samma sak som sqft_living och då kan korrelera (detta kan "förvirra" modellen över vilken som egentligen är viktig) Ridge verkar lösa detta automatiskt genom att krympa ner vikterna så de inte blir så extrema

## RANDOM FOREST

In [100]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor()
model_rf.fit(X_train, y_train)

y_pred = model_rf.predict(X_test)
y_pred[:10]

array([1187047.44      ,  557290.64      ,  713164.5       ,
        247569.53133332,  554955.13      ,  409080.58625   ,
        353936.5       ,  245739.62222222,  458248.8       ,
        705125.05      ])

In [101]:
y_test[:10].values

array([1225000.,  496752.,  612500.,  265000.,  615000.,  432000.,
        305000.,  405000.,  349000.,  839000.])

In [102]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"{mae = }")
print(f"{mse = }")
print(f"{rmse = }")

mae = 163098.15603886702
mse = 79859694330.08368
rmse = np.float64(282594.57590350823)


## LINEAR REGRESSION VALUES
    mae = 158370.37304234502 - BÄST
    mse = 53255714398.187004
    rmse = np.float64(230771.99656411304) - BÄST

## RANDOM FOREST
    mae = 163098.15603886702
    mse = 79859694330.08368
    rmse = np.float64(282594.57590350823)

## RIDGECV
    mae: 158590.13972095627 
    mse: 53385167885.37591 
    rmse: np.float64(231052.305518417)